version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errorlint
    - forbidigo
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
            - '!**/test/**/*'
          allow:
            - $gostd
            - github.com
            - gopkg.in
        test:
          files:
            - $test
          allow:
            - $gostd
            - github.com
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - err113
          - errcheck
          - funlen
          - gochecknoglobals
          - gocyclo
          - gosec
          - lll
          - scopelint
        path: _test\.go
    paths:
      - var
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - var
      - third_party$
      - builtin$
      - examples$
